In [4]:
import pandas as pd

In [6]:
file_path = 'diabetes_prediction_dataset.csv'
data = pd.read_csv(file_path)

In [12]:
!pip install tensorflow

In [13]:
import tensorflow as tf
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import datetime
import shutil
import os

## Basic tensor operations 

In [15]:
# Create a simple tensor
tensor_a = tf.constant([[1, 2], [3, 4]])
tensor_b = tf.constant([[5, 6], [7, 8]])

print("Tensor A:", tensor_a)
print("Tensor B:", tensor_b)

Tensor A: tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Tensor B: tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)


In [20]:
# Addition
tensor_sum = tf.add(tensor_a, tensor_b)
print("Addition:\n", tensor_sum)

Addition:
 tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


In [22]:
# Subtraction
tensor_sub = tf.subtract(tensor_a, tensor_b)
print("Subtraction:\n", tensor_sub)

Subtraction:
 tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32)


In [24]:
# Multiplication
tensor_mul = tf.multiply(tensor_a, tensor_b)
print("Element-wise Multiplication:\n", tensor_mul)

Element-wise Multiplication:
 tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


In [26]:
# Matrix Multiplication
tensor_matmul = tf.matmul(tensor_a, tensor_b)
print("Matrix Multiplication:\n", tensor_matmul)

Matrix Multiplication:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [28]:
# Reshape tensor
tensor_reshape = tf.reshape(tensor_a, [1, 4])
print("Reshaped Tensor A:\n", tensor_reshape)

Reshaped Tensor A:
 tf.Tensor([[1 2 3 4]], shape=(1, 4), dtype=int32)
